--
-- Table structure for table Poems
--

DROP TABLE IF EXISTS Writings;
CREATE TABLE Writings (
  ID Serial NOT NULL,
  TYPE varchar (255) NOT NULL,
  TITLE varchar(255),
  AUTHOR varchar(255)NOT NULL,
  YEAR int NOT NULL,
  TEXT text NOT NULL,
  PRIMARY KEY (ID)
);


INSERT INTO Writings (Type, Title, Author, Year, Text)VALUES
('Poems','The Road Not Taken','Robert Frost',1916,'Two roads diverged in a yellow wood,\nAnd sorry I could not travel both\nAnd be one traveler, long I stood\nAnd looked down one as far as I could\nTo where it bent in the undergrowth;\n\nThen took the other, as just as fair,\nAnd having perhaps the better claim,\nBecause it was grassy and wanted wear;\nThough as for that the passing there\nHad worn them really about the same,\n\nAnd both that morning equally lay\nIn leaves no step had trodden black.\nOh, I kept the first for another day!\nYet knowing how way leads on to way,\nI doubted if I should ever come back.\n\nI shall be telling this with a sigh\nSomewhere ages and ages hence:\nTwo roads diverged in a wood, and I—\nI took the one less traveled by,\nAnd that has made all the difference.'),
('Poems','A Dream Within A Dream','Edgar Allan Poe',1849,'Take this kiss upon the brow!\nAnd, in parting from you now,\nThus much let me avow —\nYou are not wrong, who deem\nThat my days have been a dream;\nYet if hope has flown away\nIn a night, or in a day,\nIn a vision, or in none,\nIs it therefore the less gone? \nAll that we see or seem\nIs but a dream within a dream.\n\nI stand amid the roar\nOf a surf-tormented shore,\nAnd I hold within my hand\nGrains of the golden sand —\nHow few! yet how they creep\nThrough my fingers to the deep,\nWhile I weep — while I weep!\nO God! Can I not grasp\nThem with a tighter clasp?\nO God! can I not save\nOne from the pitiless wave?\nIs all that we see or seem\nBut a dream within a dream?'),
('Poems','The Owl And The Pussycat','Edward Lear',1871,'The Owl and the Pussycat went to sea\nIn a beautiful pea green boat,\nThey took some honey, and plenty of money,\nWrapped up in a five pound note.\nThe Owl looked up to the stars above,\nAnd sang to a small guitar,\n‘O lovely Pussy! O Pussy my love,\nWhat a beautiful Pussy you are,\nYou are,\nYou are!\nWhat a beautiful Pussy you are!’\n\nPussy said to the Owl, ‘You elegant fowl!\nHow charmingly sweet you sing!\nO let us be married! Too long we have tarried:\nBut what shall we do for a ring?’\nThey sailed away, for a year and a day,\nTo the land where the Bong-tree grows\nAnd there in a wood a Piggy-wig stood\nWith a ring at the end of his nose,\nHis nose,\nHis nose,\nWith a ring at the end of his nose.\n\n‘Dear pig, are you willing to sell for one shilling\nYour ring?’ Said the Piggy, ‘I will.’\nSo they took it away, and were married next day\nBy the Turkey who lives on the hill.\nThey dined on mince, and slices of quince,\nWhich they ate with a runcible spoon;\nAnd hand in hand, on the edge of the sand,\nThey danced by the light of the moon,\nThe moon,\nThe moon,\nThey danced by the light of the moon.'),
('Poems','All The World''s A Stage','William Shakespeare',1623,'All the world''s a stage,\nAnd all the men and women merely Players;\nThey have their exits and their entrances,\nAnd one man in his time plays many parts,\nHis Acts being seven ages. At first, the infant,\nMewling and puking in the nurse''s arms.\nThen the whining schoolboy, with his satchel\nAnd shining morning face, creeping like snail\nUnwillingly to school. And then the lover,\nSighing like furnace, with a woeful ballad\nMade to his mistress'' eyebrow. Then a soldier,\nFull of strange oaths and bearded like the pard,\nJealous in honor, sudden and quick in quarrel,\nSeeking the bubble reputation\nEven in the cannon''s mouth. And then the justice,\nIn fair round belly with good capon lined,\nWith eyes severe and beard of formal cut,\nFull of wise saws and modern instances;\nAnd so he plays his part. The sixth age shifts\nInto the lean and slippered pantaloon,\nWith spectacles on nose and pouch on side;\nHis youthful hose, well saved, a world too wide\nFor his shrunk shank, and his big manly voice,\nTurning again toward childish treble, pipes\nAnd whistles in his sound. Last scene of all,\nThat ends this strange eventful history,\nIs second childishness and mere oblivion,\nSans teeth, sans eyes, sans taste, sans everything.'),
('Poems','The Rainbow','Christina Rossetti',1862,'Boats sail on the rivers,\nAnd ships sail on the seas;\nBut clouds that sail across the sky\nAre prettier far than these.\n\nThere are bridges on the rivers,\nAs pretty as you please;\nBut the bow that bridges heaven,\nAnd overtops the trees,\nAnd builds a road from earth to sky,\nIs prettier far than these.'),
('Poems','Footprints In The Sand','Mary Stevenson',1939,'One night I dreamed I was walking\nalong the beach with the Lord.\nMany scenes from my life flashed across the sky.\nIn each scene I noticed footprints in the sand.\nSometimes there were two sets of footprints,\nother times there were one set of footprints.\n\nThis bothered me because I noticed that\nduring the low periods of my life, when I was\nsuffering from anguish, sorrow or defeat,\nI could see only one set of footprints.\n\nSo I said to the Lord,”You promised me\nLord, that if I followed you,\nyou would walk with me always.\nBut I have noticed that during the most trying periods\nof my life there have only been\none set of footprints in the sand.\nWhy, when I needed you most,\nyou have not been there for me?”\n\nThe Lord replied,\n“The times when you have\nseen only one set of footprints,\nis when I carried you.”'),
('Poems','The Caterpillar','Christina Rosetti',1872,'Brown and furry\nCaterpillar in a hurry,\nTake your walk\nTo the shady leaf or stalk,\nMay no toad spy you,\nMay the little birds pass by you;\nSpin and die,\nTo live again a butterfly.'),
('Poems','The Elephant','Hilaire Belloc',1907,'When people call this beast to mind,\nThey marvel more and more\nAt such a little tail behind,\nSo large a trunk before.'),
('Poems','The Test','Eliza R. Snow',1850,'I had a message from the Lord,\nWhich I will give you, Brother Ford:\n‘Twas whispered in my ear,\nWith feelings of Imparted good\nChaste as the dew on Zion’s flood,\nWhen first the meadows rear.\n\n‘This world’s a wilderness of woe,\nWhere tears of sorrow ever flow,\nAnd mourning fills the air.\nWhile pestilence on wings of death,\nScatters the pestilential breath,\nAnd makes it in the air.\n\n‘This earth will be as by a fire,\nAnd none escape the dreadful pyre,\nWho mock the sacred word.\nWhile those who sleep in holy rest,\nWill hear a voice that wakes the just,\nProclaim them saints of God.\n\n‘Arise! for lo! the Bridegroom’s nigh!\nAnd then the nations all shall cry,\nThe Bridegroom doth appear.\nFor Him, that sat upon the Throne,\nA Kingdom shall to Him be given,\nAnd saints and angels sing.\n\n‘Arise and trim your lamps, I say,\nAnd see you keep the narrow way\nThat leads to joys on high.\nWhen Zion’s saviors all return,\nTo see mount Zion in a blaze,\nAnd Israel’s foes in death.\n\n‘Rejoice, ye saints, and shout for joy!\nThe day of Christ’s second advent’s nigh!\nThe prince of peace will come!\nAnd holy angels then will say,\nTo saints in heaven, Behold the Day!\nThe Lamb of God’s the Son.\n\n‘Go forth, ye heralds of the Cross,\nYe saviors of the world; ye saints of God,\nFor unto you, a kingdom is reserved:\nThe great Jehovah’s sons and heirs,\nThe judges of all nations!\nPrepare, prepare, for God will bring\nThe saints to stand before the king,\nAnd nations at His feet.’\n\nI heard the subject more complete;\nAnd will now give you all to eat;\nAnd Brother Ford, my friend,\nI’ve given you from the Lord,\nA message from the heavens;\nYou’ll see its truth and error.'),
('Poems','My Handcart Boy','Susan Evans McCloud',1857,'His boyish hands, now dead and gone,\nThat''s all I have of John;\nJust hands, strong hands with sunburned skin\nAnd calloused palms that long have been\nNo longer than to me to him,\nAs strong and safe and sure,\nAs sure as my, "Here''s mama''s hand,"\nTo lead him through a store,\nAs safe as Father''s guiding words,\n"Sit down, son, here''s a chore,"\nAnd sure as Heaven''s listening ear,\nAnd Christ''s own words, "What is it, dear?\nPlease tell me more!"\n\nIt''s all I have of Johnny, Lord,\nIt''s all I ever see,\nHis smile of joy, his carefree laugh,\nThe loving, caring me.\nHe was not made for dying young,\nHe was made to live.\nHe was my son, my only one,\nAnd I''ve so much to give\nMy empty arms, my aching heart,\nMy tears of love for him.\nThere''s so much life that I can''t start\nWithout my boy, my Jim.\n\nPlease take my boy, my loving boy,\nIn these strong hands of Yours,\nAnd lead him down a golden street,\nUpon a golden shore,\nAnd let him stand beside the throne\nWhere You will shine so bright\nAnd smile at him with love and pride\nTo be the Handcart Boy.'),
('Famous Quotes', NULL,'Dr. Seuss',1990,'"You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose."'),
('Famous Quotes', NULL,'Eleanor Roosevelt',0,'"The future belongs to those who believe in the beauty of their dreams."'),
('Famous Quotes', NULL,'C. S. Lewis',0,'"You are never too old to set another goal or to dream a new dream." '),
('Famous Quotes', NULL,'Kahlil Gibran',1923,'"You are the bows from which your children as living arrows are sent forth." '),
('Famous Quotes', NULL,'Steve Jobs',1995,'"The only way to do great work is to love what you do."'),
('Famous Quotes', NULL,'Abraham Lincoln',0,'"The best way to predict the future is to create it." '),
('Famous Quotes', NULL,'Mahatma Gandhi',0,'"Be the change that you wish to see in the world."'),
('Famous Quotes', NULL,'Winston Churhill',0,'"Success is not final, failure is not fatal: It is the courage to continue that counts."'),
('Famous Quotes', NULL,'Albert Einstein',0,'"In the middle of every difficulty lies opportunity."'),
('Famous Quotes', NULL,'Franklin D. Roosevelt',1933,'"The only limit to our realization of tomorrow will be our doubts of today."'),
('Historical Writings','The Preamble to the United States Constitution','Founding Fathers',1788,'We the People of the United States, in Order to form a more perfect Union, establish Justice, insure domestic Tranquility, provide for the common defence, promote the general Welfare, and secure the Blessings of Liberty to ourselves and our Posterity, do ordain and establish this Constitution for the United States of America.'),
('Historical Writings','I Have a Dream','Martin Luther King Jr.',1963,'I say to you today, my friends, so even though we face the difficulties of today and tomorrow, I still have a dream. It is a dream deeply rooted in the American dream... I have a dream that one day this nation will rise up and live out the true meaning of its creed: ''We hold these truths to be self-evident, that all men are created equal.'),
('Historical Writings','The Gettysburg Address','Abraham Lincoln',1863,'Four score and seven years ago our fathers brought forth on this continent, a new nation, conceived in Liberty, and dedicated to the proposition that all men are created equal.'),
('Historical Writings','The Declaration of Independence','Thomas Jefferson',1776,'We hold these truths to be self-evident, that all men are created equal, that they are endowed by their Creator with certain unalienable Rights, that among these are Life, Liberty, and the pursuit of Happiness.'),
('Historical Writings','The Sermon on the Mount','Jesus Christ',0,'Blessed are the poor in spirit, for theirs is the kingdom of heaven... Blessed are the meek, for they will inherit the earth... Blessed are the merciful, for they will be shown mercy...'),
('Historical Writings','The Emancipation Proclamation','Abraham Lincoln',1863,'That on the first day of January, in the year of our Lord one thousand eight hundred and sixty-three, all persons held as slaves within any State or designated part of a State, the people whereof shall then be in rebellion against the United States, shall be then, thenceforward, and forever free.'),
('Historical Writings','The Universal Declaration of Human Rights','United Nations General Assembly',1948,'All human beings are born free and equal in dignity and rights. They are endowed with reason and conscience and should act towards one another in a spirit of brotherhood.'),
('Historical Writings','The Star-Spangled Banner','Francis Scott Key',1814,'O say can you see by the dawn''s early light. What so proudly we hailed at the twilight''s last gleaming. Whose broad stripes and bright stars through the perilous fight. O''er the ramparts we watched, were so gallantly streaming?\nAnd the rocket''s red glare, the bombs bursting in air. Gave proof through the night that our flag was still there\nO say does that star-spangled banner yet wave. O''er the land of the free and the home of the brave'),
('Historical Writings','The Mayflower Compact','Pilgrims aboard the Mayflower',1620,'In the name of God, Amen. We whose names are underwritten, having undertaken for the glory of God, and advancement of the Christian faith and honor of our King and Country, a voyage to plant the first colony in the northern parts of Virginia.'),
('Historical Writings','The Four Freedoms Speech','Franklin D. Roosevelt',1941,'In the future days, which we seek to make secure, we look forward to a world founded upon four essential human freedoms... Freedom of speech and expression... Freedom of every person to worship God in his own way... Freedom from want... Freedom from fear.'),
('Scriptures',NULL,'2 Nephi 25:26',0,'26 And we talk of Christ, we rejoice in Christ, we preach of Christ, we prophesy of Christ, and we write according to our prophecies, that our children may know to what source they may look for a remission of their sins.'),
('Scriptures',NULL,'Alma 37:6',0,'6 Now ye may suppose that this is\nfoolishness in me; but behold I say unto\nyou, that by small and simple things are\ngreat things brought to pass; and small\nmeans in many instances doth confound the\nwise.'),
('Scriptures',NULL,'Moroni 10:5',0,'5 And by the power of the Holy Ghost ye may know the truth of all things.'),
('Scriptures',NULL,'3 Nephi 18:15',0,'15 Verily, verily, I say unto you, ye must watch and pray always, lest ye be tempted by the devil, and ye be led away captive by him.'),
('Scriptures',NULL,'D&C 89:18-21',0,'18 And all the saints who remember to keep and do these sayings, walking in obedience to the commandments, shall receive health in their navel and marrow to their bones.\n19 And shall find wisdom and great treasures of knowledge, even hidden treasures;\n20 And shall run and not be weary, and shall walk and not faint.\n21 And I, the Lord, give unto them a promise, that the destroying angel shall pass by them, as the children of Israel, and not slay them. Amen.'),
('Scriptures',NULL,'Proverbs 3:5-6',0,'5 Trust int he Lord with all thine heart; and lean not unto thine own understanding.\n6 In all thy ways acknowledge him, and he shall direct thy paths.'),
('Scriptures',NULL,'Psalms 119:105',0,'105 Thy word is a lamp unto my feet, and a light unto my path.'),
('Scriptures',NULL,'Matthew 22:39',0,'39 And the second is like unto it, Thou shalt love thy neighbour as theyself.'),
('Scriptures',NULL,'Matthew 5:16',0,'16 Let your light so shine before men, that they may see your good works, and glorify your Father which is in heaven.'),
('Scriptures',NULL,'Philippians 4:13',0,'13 I can do all things Christ which strengtheneth me.')

;

DROP TABLE IF EXISTS User_Profiles;
CREATE TABLE User_Profiles (
  ID serial NOT NULL,
  Username char(55) NOT NULL,
  Full_Name char(55) NOT NULL,
  DOB char(55) NOT NULL,
  Badges int NOT NULL,
  PRIMARY KEY (ID)
);

INSERT INTO User_Profiles (Username, Full_Name, DOB, Badges) VALUES ('Jason','Jason_Beach','11/03/1986',2),
('Loni','Loni_Beach','01/29/1987',4),
('Laelia','Laelia_Beach','',2),
('Avonlea','Avonlea_Beach','',5),
('Talia','Talia_Beach','',5),
('Cohen','Cohen_Beach','',1);

